#!/bin/bash

# This script runs under fakeroot.  The fakeroot utility has 
# problems under 64-bit/multi-processor/preemptive kernel, so
# we run it only when necessary.

source $KERNEL_DIR/.config

if [ "$BRCM_FULL_CHIP_NAME" = "6858B0" ]; then
    CHIP_REV_SUFIX="_b0"
else
    CHIP_REV_SUFIX=""
fi

if [ -f $PROFILE_DIR/../cfe/cfe${BRCM_CHIP}ram_emmc${CHIP_REV_SUFIX}.bin ]; then
    rm -f $TARGET_BOOTFS/cferam.000
    cp $PROFILE_DIR/../cfe/cfe${BRCM_CHIP}ram_emmc${CHIP_REV_SUFIX}.bin $TARGET_BOOTFS/cferam.000
    rm -f $PROFILE_DIR/filestruct_full_emmc.bin
    $PROFILE_DIR/../buildUBI -u "" -m $PROFILE_DIR/metadata.bin -f $PROFILE_DIR/filestruct_full_emmc.bin -t $TARGET_BOOTFS -y ""
    #### eMMC ext4 
    FS_SIZE_INC=2
    FS_SIZE=`du -sh $TARGET_FS | cut -d'M' -f1`
    FS_SIZE_TARGET=$(( $FS_SIZE*$FS_SIZE_INC ))M
    rm -f $PROFILE_DIR/rootfs.ext4
    echo "Starting building ext4 actual-size:${FS_SIZE}M target-size:${FS_SIZE_TARGET}"
    $HOSTTOOLS_DIR/local_install/make_ext4fs -l $FS_SIZE_TARGET $PROFILE_DIR/rootfs.ext4 $TARGET_FS
    resize2fs -M $PROFILE_DIR/rootfs.ext4
    echo "Done building ext4"
fi
