
#ifndef	_SC_DRV_H_
#define	_SC_DRV_H_


#define SC_DRV_STR  "scDrv"
#define SC_DRV_FD_NAME_STR  "/dev/"SC_DRV_STR


typedef enum
{
    SC_DRV_IOCTL_NONE_CMD = 0,
    SC_DRV_IOCTL_GET_ETH_PORT_STATUS_CMD,
    SC_DRV_IOCTL_GET_ETH_PORT_BY_HOST_MAC_CMD,
    SC_DRV_IOCTL_GET_ETH_PORT_STATISTICS_CMD,
    SC_DRV_IOCTL_GET_GPIO_STATUS_CMD,
    SC_DRV_IOCTL_GET_GPIO_EVENT_CMD,
    SC_DRV_IOCTL_SET_OUTPUT_CMD,
#if defined(SUPPORT_USB_STORAGE) || defined(SUPPORT_USB_PRINTER) || defined(CONFIG_SUPPORT_3G)  
    SC_DRV_IOCTL_SET_OUTPUT_USB_STATE_CMD,
    SC_DRV_IOCTL_GET_SPECIFYTYPE_USB_STATE,
#endif
    SC_DRV_IOCTL_GET_ETH_PORT_CHANGED_CMD,
	SC_DRV_IOCTL_GET_SENSOR_EVENT,
	SC_DRV_IOCTL_GET_SENSOR_EVENT_W,
#ifdef CONFIG_SUPPORT_ENERGY_SAVING
	SC_DRV_IOCTL_SET_ENERGY_SAVING_MODE,
#endif
#ifdef VOX25
	SC_DRV_IOCTL_SET_OUTPUT_CMD_FORCED,
#endif
#ifdef CONFIG_SUPPORT_5G_QD
    SC_DRV_IOCTL_RESET_QD_WIFI,
#endif
    SC_DRV_IOCTL_ADD_QOS_DEV_LIST,
    SC_DRV_IOCTL_CLR_QOS_DEV_LIST,
    SC_DRV_IOCTL_GET_TCPACKPRIO_STATUS,
    SC_DRV_IOCTL_SET_TCPACKPRIO_ENABLE,
    SC_DRV_IOCTL_SET_TCPACK_XTMPRIO,
    SC_DRV_IOCTL_SET_TCPACK_ETHPRIO,
#ifdef CONFIG_SUPPORT_SEC_BOOT
    SC_DRV_IOCTL_GET_SEC_AES_KEY,
    SC_DRV_IOCTL_GET_SEC_RSA_KEY,
#endif
    SC_DRV_IOCTL_GET_OUTPUT_CMD,
#ifdef CONFIG_SUPPORT_IPERF
    SC_DRV_IOCTL_SET_IPERF_CREATE_STREAM = 1000,
    SC_DRV_IOCTL_GET_IPERF_CREATE_STREAM_STATE,
    SC_DRV_IOCTL_GET_IPERF_UPDATE_RESULT,
    SC_DRV_IOCTL_SET_IPERF_TEST_DONE,
    SC_DRV_IOCTL_SET_IPERF_TEST_RUN,
#endif

} SC_DRV_IOCTL_CMD;


#endif /* _SC_DRV_H_ */

