#ifndef __DSL_COMMON_H__
#define __DSL_COMMON_H__

typedef struct adsl_info_s{
	char 	status[128];
	int	down_stream;
	int	up_stream;
	int	down_currstream;
	int	up_currstream;
	int	upbokle;
	unsigned long total_start;
	unsigned long show_time_start;
    unsigned long show_time_total;
    unsigned long last_show_time_start;
	unsigned long curr_day_start;
	unsigned long quarter_hour_start;
	unsigned int last_change;
	unsigned int t_blocks;
	unsigned int r_blocks;
	unsigned int celldelin;
	unsigned int link_retrain;
	unsigned int init_err;
	unsigned int init_timeout;
	unsigned int lof;
	unsigned int err_secs;
    //last showtime
	unsigned int last_showtime_r_blocks;
	unsigned int last_showtime_t_blocks;
	unsigned int last_showtime_celldelin;
	unsigned int last_showtime_link_retrain;
	unsigned int last_showtime_init_err;
	unsigned int last_showtime_init_timeout;
	unsigned int last_showtime_lof;
	unsigned int last_showtime_err_secs;
	unsigned int last_showtime_d_ses;
	unsigned int last_showtime_fec_errs;
	unsigned int last_showtime_atuc_fec_errs;
	unsigned int last_showtime_hec_errs;
	unsigned int last_showtime_atuc_hec_errs;
	unsigned int last_showtime_crc_errs;
	unsigned int last_showtime_atuc_crc_errs;
    //showtime
	unsigned int showtime_r_blocks;
	unsigned int showtime_t_blocks;
	unsigned int showtime_celldelin;
	unsigned int showtime_link_retrain;
	unsigned int showtime_init_err;
	unsigned int showtime_init_timeout;
	unsigned int showtime_lof;
	unsigned int showtime_err_secs;
	unsigned int showtime_d_ses;
	unsigned int showtime_fec_errs;
	unsigned int showtime_atuc_fec_errs;
	unsigned int showtime_hec_errs;
	unsigned int showtime_atuc_hec_errs;
	unsigned int showtime_crc_errs;
	unsigned int showtime_atuc_crc_errs;
    //quarter hour
	unsigned int quarter_hour_r_blocks;
	unsigned int quarter_hour_t_blocks;
	unsigned int quarter_hour_celldelin;
	unsigned int quarter_hour_link_retrain;
	unsigned int quarter_hour_init_err;
	unsigned int quarter_hour_init_timeout;
	unsigned int quarter_hour_lof;
	unsigned int quarter_hour_err_secs;
	unsigned int quarter_hour_d_ses;
	unsigned int quarter_hour_fec_errs;
	unsigned int quarter_hour_atuc_fec_errs;
	unsigned int quarter_hour_hec_errs;
	unsigned int quarter_hour_atuc_hec_errs;
	unsigned int quarter_hour_crc_errs;
	unsigned int quarter_hour_atuc_crc_errs;
    //current day
	unsigned int curr_r_blocks;
	unsigned int curr_t_blocks;
	unsigned int curr_celldelin;
	unsigned int curr_link_retrain;
	unsigned int curr_init_err;
	unsigned int curr_init_timeout;
	unsigned int curr_lof;
	unsigned int curr_err_secs;
	unsigned int curr_d_ses;
	unsigned int curr_fec_errs;
	unsigned int curr_atuc_fec_errs;
	unsigned int curr_hec_errs;
	unsigned int curr_atuc_hec_errs;
	unsigned int curr_crc_errs;
	unsigned int curr_atuc_crc_errs;
    // quality
	unsigned int d_k;
	unsigned int u_k;
	unsigned int d_r;
	unsigned int u_r;
	float d_s;
	float u_s;
	unsigned int d_d;
	unsigned int u_d;
	long d_delay;
	long u_delay;
    // total error
	unsigned int d_ses;
	unsigned int u_ses;
	unsigned int d_es;
	unsigned int u_es;
	unsigned int d_uas;
	unsigned int u_uas;
    // Bearer
	unsigned int d_sf;
	unsigned int u_sf;
	unsigned int d_sf_err;
	unsigned int u_sf_err;
	unsigned int d_rs;
	unsigned int u_rs;
	unsigned int d_rs_corr;
	unsigned int u_rs_corr;
	unsigned int d_rs_uncorr;
	unsigned int u_rs_uncorr;
	unsigned int d_hec;
	unsigned int u_hec;
    unsigned int d_fec;
    unsigned int u_fec;
    unsigned int d_crc;
    unsigned int u_crc;
	unsigned int d_ocd;
	unsigned int u_ocd;
	unsigned int d_lcd;
	unsigned int u_lcd;
	unsigned int d_total_cells;
	unsigned int u_total_cells;
	unsigned int d_data_cells;
	unsigned int u_data_cells;
	unsigned int d_bit_err;
	unsigned int u_bit_err;
    // total&showtime
	unsigned int crc_errs;
	unsigned int atuc_crc_errs;
	unsigned int hec_errs;
	unsigned int atuc_hec_errs;
	unsigned int fec_errs;
	unsigned int atuc_fec_errs;
	unsigned int show_crc_errs;
	unsigned int show_fec_errs;
	unsigned int d_quarter_hour_crc_errs;
	unsigned int u_quarter_hour_crc_errs;
	unsigned int r_total_cells;
	unsigned int t_total_cells;
	unsigned int num_of_cuts;
	char 	c_profile[16];
	char 	down_attenuation[16];
	char 	up_attenuation[16];
	char    up_noise[16];
	char    down_noise[16];
	char 	down_power[16];
	char 	up_power[16];
	char 	u_trell[16];
	char 	d_trell[16];
	char 	down_snrmpb[16];
	char 	up_snrmpb[16];
	char 	standard[16];
	char 	annex[16];
	char 	tps_tc[16];
	char    power_state[16];
	char 	module_type[16];
    char    LATNus[25];
    char    LATNds[25];
    char    SATNus[25];
    char    SATNds[25];
	unsigned int HLOGGds;
	unsigned int HLOGGus;
    char    HLOGpsds[2560];
    char    HLOGpsus[2560];
    char    LineEncoding[16];
}adsl_info_t;
typedef struct dsl_stats_s 
{
    unsigned long rx_bytes;
    unsigned long tx_bytes;
    unsigned long rx_packets;
    unsigned long tx_packets;
    unsigned long rx_oam;
    unsigned long tx_oam;
    unsigned long rx_asm;
    unsigned long tx_asm;
    unsigned long rx_cell_errors;
    unsigned long rx_packet_errors;
} dsl_stats_t;

int val_get_dsl_wan_stats(int port_id, dsl_stats_t **dsl_stats);
int val_start_adsl(int wan_id);
int val_start_dsl_if(int wan_id);
int val_stop_dsl_if(int wan_id);
int val_get_adsl_info(adsl_info_t *adsl);
int val_get_dsl_status(adsl_info_t **adsl);
int val_get_dsl_status_non_buffered(adsl_info_t **adsl);
char* val_get_dsl_UpAttenuation();
char* val_get_dsl_DownAttenuation();
char* val_get_dsl_UpNoise();
char* val_get_dsl_DownNoise();
int val_get_dsl_UpStream();
char* val_get_dsl_trans_mode();
int val_get_dsl_version(char* version);
int val_stop_adsl_phy(void);
int val_start_adsl_phy_cfg(void);
int val_stop_adsl_phy_cfg(void);
int val_dsl_clear_counter(void);

int val_dsl_get_dsl_init_mode(int wan_id);
#endif
