#!/bin/sh
echo Installing QoS-helper kernel-module act_connmark...
modprobe act_connmark || {
	apt-get install dkms
	dpkg -i act-connmark-dkms*.deb
}

echo Setting up forwarding and NAT...
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -j MASQUERADE

echo Creating /etc/config directory...
mkdir -p /etc/config

echo Creating /etc/config/hotspotd if not present...
[ -f "/etc/config/hotspotd" ] || cp conf/hotspotd /etc/config

echo You need to configure your instance of hotspotd now.
read -p "Press return to continue." pause
editor /etc/config/hotspotd
echo

echo Setup your public interface and configure it.
echo e.g.: ifconfig IFACE 192.168.56.1 255.255.255.0
echo e.g.: ifconfig IFACE up
read -p "Press return when you are done." pause
echo

echo Setup DHCP and DNS services on the interface and start them.
echo e.g.: install and configure dnsmasq
read -p "Press return when you are done." pause
echo

./hotspotd -evv
