#!/bin/sh /etc/rc.common
START=7
USE_PROCD=1
SERVICE_DAEMONIZE=1

service_triggers() {
        procd_open_trigger
       	procd_add_event_name_trigger Services.Local.Media.DLNA 100 SERVICES_LOCAL_MEDIA_DLNA_DISABLED /etc/init.d/dlna stop
       	procd_add_event_name_trigger Services.Local.Media.DLNA 100 SERVICES_LOCAL_MEDIA_DLNA_MODIFIED /etc/init.d/dlna restart
       	procd_add_event_name_trigger Services.Local.Media.DLNA 100 SERVICES_LOCAL_MEDIA_DLNA_ENABLED /etc/init.d/dlna restart
#       	procd_add_event_trigger Interfaces.Physical.Data.USB 1000 /etc/init.d/dlna restart
       	procd_close_trigger
}
                        
start_service() {
    /usr/sbin/rc mediaserver start;
}

stop_service() {
    /usr/sbin/rc mediaserver stop;
}

