#ifndef _CAL_FON_H_
#define _CAL_FON_H_

char *cal_fon_get_enable(void);
int cal_fon_set_enable(char *value);
char *cal_fon_get_availability(void);
int cal_fon_set_availability(char *value);
char *cal_fon_get_max_assoc_users(void);
int cal_fon_set_max_assoc_users(char *value);
char *cal_fon_get_max_login_users(void);
int cal_fon_set_max_login_users(char *value);
char *cal_fon_get_ssid_max_assoc_users(void);
int cal_fon_set_ssid_max_assoc_users(char *value);
char *cal_fon_get_eapssid_max_assoc_users(void);
int cal_fon_set_eapssid_max_assoc_users(char *value);
char *cal_fon_get_ssid(void);
int cal_fon_set_ssid(char *value);
char *cal_fon_get_ssid5(void);
int cal_fon_set_ssid5(char *value);
char *cal_fon_get_eap_ssid(void);
int cal_fon_set_eap_ssid(char *value);
char *cal_fon_get_ssid_sec(void);
int cal_fon_set_ssid_sec(char *value);
char *cal_fon_get_eapssid_sec(void);
int cal_fon_set_eapssid_sec(char *value);
char *cal_fon_get_eap_ssid5(void);
int cal_fon_set_eap_ssid5(char *value);
char *cal_fon_get_activation_delay(void);
int cal_fon_set_activation_delay(char *value);
char *cal_fon_get_uam_server(void);
int cal_fon_set_uam_server(char *value);
char *cal_fon_get_uam_secret(void);
int cal_fon_set_uam_secret(char *value);
char *cal_fon_get_static_white_list(void);
int cal_fon_set_static_white_list(char *value);
char *cal_fon_get_dynamic_white_list(void);
int cal_fon_set_dynamic_white_list(char *value);
char *cal_fon_get_eap(void);
int cal_fon_set_eap(char *value);
char *cal_fon_get_eap5(void);
int cal_fon_set_eap5(char *value);
char *cal_fon_get_eap_server(void);
int cal_fon_set_eap_server(char *value);
char *cal_fon_get_eap_server_secret(void);
int cal_fon_set_eap_server_secret(char *value);
char *cal_fon_get_eap_server_auth_port(void);
int cal_fon_set_eap_server_auth_port(char *value);
char *cal_fon_get_eap_server_acc_port(void);
int cal_fon_set_eap_server_acc_port(char *value);
char *cal_fon_get_bandwidth_min(void);
int cal_fon_set_bandwidth_min(char *value);
char *cal_fon_get_bandwidth_ingress(void);
int cal_fon_set_bandwidth_ingress(char *value);
char *cal_fon_get_bandwidth_egress(void);
int cal_fon_set_bandwidth_egress(char *value);
char *cal_fon_get_bandwidth_percent(void);
int cal_fon_set_bandwidth_percent(char *value);
char *cal_fon_get_idle_timeout(void);
int cal_fon_set_idle_timeout(char *value);
char *cal_fon_get_loc_name(void);
int cal_fon_set_loc_name(char *value);
char *cal_fon_get_ven_class(void);
int cal_fon_set_ven_class(char *value);
char *cal_fon_get_user_select(void);
int cal_fon_set_user_select(char *value);
char *cal_fon_get_service_status(void);
char *cal_fon_get_l2tp_enable(void);
int cal_fon_set_l2tp_enable(char *value);
char *cal_fon_get_l2tp_server(void);
int cal_fon_set_l2tp_server(char *value);
char *cal_fon_get_l2tp_start_rtx_delay(void);
int cal_fon_set_l2tp_start_rtx_delay(char *value);
char *cal_fon_get_l2tp_start_max_retry(void);
int cal_fon_set_l2tp_start_max_retry(char *value);
char *cal_fon_get_l2tp_pppd_timeout(void);
int cal_fon_set_l2tp_pppd_timeout(char *value);
char *cal_fon_get_l2tp_hello_delay(void);
int cal_fon_set_l2tp_hello_delay(char *value);
char *cal_fon_get_l2tp_rtx_delay(void);
int cal_fon_set_l2tp_rtx_delay(char *value);
char *cal_fon_get_l2tp_max_retry(void);
int cal_fon_set_l2tp_max_retry(char *value);
char *cal_fon_get_l2tp_lcp_echo_interval(void);
int cal_fon_set_l2tp_lcp_echo_interval(char *value);
char *cal_fon_get_l2tp_lcp_echo_fail(void);
int cal_fon_set_l2tp_lcp_echo_fail(char *value);

char *cal_fon_get_service_id(void);
int cal_fon_set_service_id(char *value);
char *cal_fon_get_ssid_vlan(void);
int cal_fon_set_ssid_vlan(char *value);
char *cal_fon_get_eapssid_vlan(void);
int cal_fon_set_eapssid_vlan(char *value);
char *cal_fon_get_ssid_tforward(void);
int cal_fon_set_ssid_tforward(char *value);
char *cal_fon_get_eapssid_tforward(void);
int cal_fon_set_eapssid_tforward(char *value);
char *cal_fon_get_gre_server(void);
int cal_fon_set_gre_server(char *value);
char *cal_fon_get_gre_ip_fragment(void);
int cal_fon_set_gre_ip_fragment(char *value);
int cal_fon_set_gre_keepalive_interval(char *value);
char *cal_fon_get_gre_keepalive_interval(void);
char *cal_fon_get_gre_timeout(void);
int cal_fon_set_gre_timeout(char *value);
char *cal_fon_get_gre_ping_timout(void);
int cal_fon_set_gre_ping_timeout(char *value);
char *cal_fon_get_gre_retry_interval(void);
int cal_fon_set_gre_retry_interval(char *value);

char *cal_fon_get_client_num(void);
char* cal_fon_get_client_counter(void);
int cal_fon_update_client_nodes(int cmax);
char* cal_fon_get_client_ssid(int id);
char *cal_fon_get_gui_enable(void);
int cal_fon_set_gui_enable(char *value);

#endif /* _CAL_FON_H_ */
