#ifndef __CAL_SPI_H__
#define __CAL_SPI_H__

char *cal_spi_get_fw_level(void);
int cal_spi_set_fw_level(char *value);
char *cal_spi_get_firewall_en(void);
int cal_spi_set_firewall_en(char *value);

/* DoS */
char *cal_dos_get_enable(void);
int cal_dos_set_enable(char *value);
char *cal_dos_get_frghdr(void);
int cal_dos_set_frghdr(char *value);
char *cal_dos_get_icmp_smurf(void);
int cal_dos_set_icmp_smurf(char *value);
char *cal_dos_get_ip_land(void);
int cal_dos_set_ip_land(char *value);
char *cal_dos_get_ip_teardrop(void);
int cal_dos_set_ip_teardrop(char *value);
char *cal_dos_get_invalid_tcp_flag(void);
int cal_dos_set_invalid_tcp_flag(char *value);
char *cal_dos_get_lan_src_ip(void);
int cal_dos_set_lan_src_ip(char *value);
char *cal_dos_get_pingofdeath(void);
int cal_dos_set_pingofdeath(char *value);
char *cal_dos_get_port_scan(void);
int cal_dos_set_port_scan(char *value);
char *cal_dos_get_port_scan_sens(void);
int cal_dos_set_port_scan_sens(char *value);
char *cal_dos_get_icmp_flood(void);
int cal_dos_set_icmp_flood(char *value);
char *cal_dos_get_icmp_flood_speed(void);
int cal_dos_set_icmp_flood_speed(char *value);
char *cal_dos_get_icmp_flood_per_ip(void);
char *cal_dos_get_guest_flood_speed(void);
int cal_dos_set_icmp_flood_per_ip(char *value);
char *cal_dos_get_icmp_flood_per_ip_speed(void);
int cal_dos_set_icmp_flood_per_ip_speed(char *value);
char *cal_dos_get_tcp_syn_flood(void);
int cal_dos_set_tcp_syn_flood(char *value);
char *cal_dos_get_tcp_syn_flood_speed(void);
int cal_dos_set_tcp_syn_flood_speed(char *value);
char *cal_dos_get_tcp_syn_flood_per_ip(void);
int cal_dos_set_tcp_syn_flood_per_ip(char *value);
char *cal_dos_get_tcp_syn_flood_per_ip_speed(void);
int cal_dos_set_tcp_syn_flood_per_ip_speed(char *value);
char *cal_dos_get_tcp_fin_flood(void);
int cal_dos_set_tcp_fin_flood(char *value);
char *cal_dos_get_tcp_fin_flood_speed(void);
int cal_dos_set_tcp_fin_flood_speed(char *value);
char *cal_dos_get_tcp_fin_flood_per_ip(void);
int cal_dos_set_tcp_fin_flood_per_ip(char *value);
char *cal_dos_get_tcp_fin_flood_per_ip_speed(void);
int cal_dos_set_tcp_fin_flood_per_ip_speed(char *value);
char *cal_dos_get_udp_flood(void);
int cal_dos_set_udp_flood(char *value);
char *cal_dos_get_udp_flood_speed(void);
int cal_dos_set_udp_flood_speed(char *value);
char *cal_dos_get_udp_flood_per_ip(void);
int cal_dos_set_udp_flood_per_ip(char *value);
char *cal_dos_get_udp_flood_per_ip_speed(void);
int cal_dos_set_udp_flood_per_ip_speed(char *value);
char *cal_dos_get_winnuke(void);
int cal_dos_set_winnuke(char *value);
char *cal_dos_get_tcp_scan(void);
int cal_dos_set_tcp_scan(char *value);
char *cal_dos_get_brdcst_src(void);
int cal_dos_set_brdcst_src(char *value);
char *cal_dos_get_syn_with_data(void);
int cal_dos_set_syn_with_data(char *value);
char *cal_dos_get_fw_block(void);
int cal_dos_set_fw_block(char *value);
char *cal_dos_get_block_time(void);
int cal_dos_set_block_time(char *value);
char *cal_dos_get_ip_spoof(void);
int cal_dos_set_ip_spoof(char *value);
char *cal_dos_get_udp_bomb(void);
int cal_dos_set_udp_bomb(char *value);
char *cal_mgnt_get_max_conntrack_num(void);
int cal_mgnt_set_max_conntrack_num(char *value);
char *cal_mgnt_get_conntrack_tcp_timeout_syn_sent(void);
int cal_mgnt_set_conntrack_tcp_timeout_syn_sent(char *value);
char *cal_mgnt_get_conntrack_tcp_timeout_syn_recv(void);
int cal_mgnt_set_conntrack_tcp_timeout_syn_recv(char *value);
char *cal_mgnt_get_conntrack_tcp_timeout_established(void);
int cal_mgnt_set_conntrack_tcp_timeout_established(char *value);
char *cal_mgnt_get_conntrack_tcp_timeout_close(void);
int cal_mgnt_set_conntrack_tcp_timeout_close(char *value);
char *cal_mgnt_get_conntrack_tcp_timeout_close_wait(void);
int cal_mgnt_set_conntrack_tcp_timeout_close_wait(char *value);
char *cal_mgnt_get_conntrack_tcp_timeout_last_ack(void);
int cal_mgnt_set_conntrack_tcp_timeout_last_ack(char *value);
char *cal_mgnt_get_conntrack_tcp_timeout_fin_wait(void);
int cal_mgnt_set_conntrack_tcp_timeout_fin_wait(char *value);
char *cal_mgnt_get_conntrack_udp_timeout_stream(void);
int cal_mgnt_set_conntrack_udp_timeout_stream(char *value);
char *cal_mgnt_get_conntrack_udp_timeout(void);
int cal_mgnt_set_conntrack_udp_timeout(char *value);
#endif
