char *cal_ntp_get_status(void);
char *cal_ntp_get_local_time(void);
/*--------------------------------*/
char *cal_ntp_get_enable(void);
int cal_ntp_set_enable(char *value);
char *cal_ntp_get_server1(void);
int cal_ntp_set_server1(char *value);
char *cal_ntp_get_server2(void);
int cal_ntp_set_server2(char *value);
char *cal_ntp_get_server3(void);
int cal_ntp_set_server3(char *value);
char *cal_ntp_get_server4(void);
int cal_ntp_set_server4(char *value);
char *cal_ntp_get_server5(void);
int cal_ntp_set_server5(char *value);
char *cal_ntp_get_timezone(void);
int cal_ntp_set_timezone(char *value);
char *cal_ntp_get_timezone_name(void);
int cal_ntp_set_timezone_name(char *value);
char *cal_ntp_get_ds_used(void);
int cal_ntp_set_ds_used(char *value);
char *cal_ntp_get_ds_start(void);
int cal_ntp_set_ds_start(char *value);
char *cal_ntp_get_ds_end(void);
int cal_ntp_set_ds_end(char *value);
char *cal_ntp_get_ds_offset(void);
int cal_ntp_set_ds_offset(char *value);
char *cal_ntp_get_refresh_fail_time(void);
int cal_ntp_set_refresh_fail_time(char *value);
char *cal_ntp_get_refresh_suc_time(void);
int cal_ntp_set_refresh_suc_time(char *value);
char *cal_ntp_get_refresh_fail_over_count(void);
int cal_ntp_set_refresh_fail_over_count(char *value);
char *cal_ntp_get_interface(void);
int cal_ntp_set_interface(char *value);
char *cal_ntp_get_client_port(void);
int cal_ntp_set_client_port(char *value);
char *cal_ntp_get_tod_time(void);
int cal_ntp_set_tod_time(char *value);
char *cal_ntp_get_timezone_override(void);
int cal_ntp_set_timezone_override(char *value);
char *cal_ntp_get_ntp_server_override(void);
int cal_ntp_set_ntp_server_override(char *value);
char *cal_ntp_get_vendor_id(void);
int cal_ntp_set_vendor_id(char *value);
int hcal_ntp_get_bind_wan_id(void);
int cal_ntp_set_version(char *value);
int cal_ntp_get_version(void);

