#!/bin/sh

# External Config
MEDIUM=$1
MEMORY=${MEMORY:-512}
VMNAME=${NAME:-hotspotd}

# Preparing
vboxmanage unregistervm $VMNAME --delete 2>/dev/null
set -ex

vboxmanage createvm --name $VMNAME --ostype Debian_64 --register
vboxmanage modifyvm $VMNAME --chipset ich9 --memory $MEMORY --rtcuseutc on --nic1 nat --nic2 hostonly --hostonlyadapter2 vboxnet0
vboxmanage storagectl $VMNAME --name SATA --add sata --controller IntelAHCI
vboxmanage storageattach $VMNAME --storagectl SATA --port 0 --device 0 --type hdd --forceunmount --medium $MEDIUM
vboxmanage export $VMNAME -o $VMNAME.ova
vboxmanage storagectl $VMNAME --name SATA --remove
vboxmanage closemedium disk $MEDIUM
vboxmanage unregistervm $VMNAME --delete
